version: "3.3"

services:
  postgres:
    image: postgres
      container_name: loginservice-database
      restart: always
      environment:
        POSTGRES_USER: loginservice
        POSTGRES_PASSWORD: Loginservice_database_password1
        POSTGRES_DB: loginservice-database