version: '2'

services:
  yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: yugabyte
    command: [ "./bin/yugabyted", 
               "start",
               "--initial_scripts_dir=/docker-entrypoint-initdb.d",
               "--daemon=false" ]
    volumes:
    - "./blankdatabasestartup.cql:/docker-entrypoint-initdb.d/init.cql"
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"

  loginservice:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: loginservice
    restart: always
    environment:
      LOGINSERVICE_DATABASE_HOST: "yugabytedb"
      LOGINSERVICE_DATABASE_PORT: 9042
      LOGINSERVICE_PORT: 5005
      LOGINSERVICE_JWT_ISSUER: "https://localhost:5005"
      LOGINSERVICE_JWT_KEY: "developmentjwtkey"
    ports:
      - 5005:5005
