version: "3"

services:
  loginservice:
    image: omvk97/loginservice
    container_name: loginservice
    restart: always
    environment:
      LOGINSERVICE_POSTGRES_CONNECTION_STRING: 
      LOGINSERVICE_PORT: 5005
      LOGINSERVICE_JWT_ISSUER: 
      LOGINSERVICE_JWT_KEY: "developmentjwtkey"
    ports:
      - 5005:5005
    depends_on:
      - postgres
